apiVersion: workflow.newrelic.upbound.io/v1alpha1
kind: Workflow
metadata:
  annotations:
    meta.upbound.io/example-id: workflow/v1alpha1/workflow
  labels:
    testing.upbound.io/example-name: foo
  name: foo
spec:
  forProvider:
    destination:
    - channelIdSelector:
        matchLabels:
          testing.upbound.io/example-name: some_channel
    issuesFilter:
    - name: filter-name
      predicate:
      - attribute: accumulations.tag.team
        operator: EXACTLY_MATCHES
        values:
        - growth
      type: FILTER
    mutingRulesHandling: NOTIFY_ALL_ISSUES
    name: workflow-example
