/*
Copyright 2024 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type CloudRuleInitParameters struct {

	// The account ID where the Pipeline Cloud Rule will be created.
	// The account ID where the Pipeline Cloud rule will be created.
	AccountID *float64 `json:"accountId,omitempty" tf:"account_id,omitempty"`

	// Additional information about the rule.
	// Provides additional information about the rule.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// The name of the rule. This must be unique within an account.
	// The name of the rule. This must be unique within an account.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The NRQL query that defines the data to be processed by this Pipeline Cloud Rule.
	// The NRQL query that defines which data will be processed by this pipeline cloud rule.
	Nrql *string `json:"nrql,omitempty" tf:"nrql,omitempty"`
}

type CloudRuleObservation struct {

	// The account ID where the Pipeline Cloud Rule will be created.
	// The account ID where the Pipeline Cloud rule will be created.
	AccountID *float64 `json:"accountId,omitempty" tf:"account_id,omitempty"`

	// Additional information about the rule.
	// Provides additional information about the rule.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// The ID of the Pipeline Cloud Rule.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// The name of the rule. This must be unique within an account.
	// The name of the rule. This must be unique within an account.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The NRQL query that defines the data to be processed by this Pipeline Cloud Rule.
	// The NRQL query that defines which data will be processed by this pipeline cloud rule.
	Nrql *string `json:"nrql,omitempty" tf:"nrql,omitempty"`
}

type CloudRuleParameters struct {

	// The account ID where the Pipeline Cloud Rule will be created.
	// The account ID where the Pipeline Cloud rule will be created.
	// +kubebuilder:validation:Optional
	AccountID *float64 `json:"accountId,omitempty" tf:"account_id,omitempty"`

	// Additional information about the rule.
	// Provides additional information about the rule.
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// The name of the rule. This must be unique within an account.
	// The name of the rule. This must be unique within an account.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The NRQL query that defines the data to be processed by this Pipeline Cloud Rule.
	// The NRQL query that defines which data will be processed by this pipeline cloud rule.
	// +kubebuilder:validation:Optional
	Nrql *string `json:"nrql,omitempty" tf:"nrql,omitempty"`
}

// CloudRuleSpec defines the desired state of CloudRule
type CloudRuleSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            CloudRuleParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider CloudRuleInitParameters `json:"initProvider,omitempty"`
}

// CloudRuleStatus defines the observed state of CloudRule.
type CloudRuleStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        CloudRuleObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// CloudRule is the Schema for the CloudRules API. Use this resource to create and manage a New Relic Pipeline Cloud Rule.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,newrelic}
type CloudRule struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.nrql) || (has(self.initProvider) && has(self.initProvider.nrql))",message="spec.forProvider.nrql is a required parameter"
	Spec   CloudRuleSpec   `json:"spec"`
	Status CloudRuleStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// CloudRuleList contains a list of CloudRules
type CloudRuleList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []CloudRule `json:"items"`
}

// Repository type metadata.
var (
	CloudRule_Kind             = "CloudRule"
	CloudRule_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: CloudRule_Kind}.String()
	CloudRule_KindAPIVersion   = CloudRule_Kind + "." + CRDGroupVersion.String()
	CloudRule_GroupVersionKind = CRDGroupVersion.WithKind(CloudRule_Kind)
)

func init() {
	SchemeBuilder.Register(&CloudRule{}, &CloudRuleList{})
}
