/*
Copyright 2026 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type CustomHeaderInitParameters struct {

	// Header name.
	// Header name
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Header Value.
	// Header value
	Value *string `json:"value,omitempty" tf:"value,omitempty"`
}

type CustomHeaderObservation struct {

	// Header name.
	// Header name
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Header Value.
	// Header value
	Value *string `json:"value,omitempty" tf:"value,omitempty"`
}

type CustomHeaderParameters struct {

	// Header name.
	// Header name
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Header Value.
	// Header value
	// +kubebuilder:validation:Optional
	Value *string `json:"value,omitempty" tf:"value,omitempty"`
}

type MonitorInitParameters struct {

	// The account in which the Synthetics monitor will be created.
	// ID of the newrelic account
	AccountID *float64 `json:"accountId,omitempty" tf:"account_id,omitempty"`

	// The multiple browsers list on which synthetic monitors will run. Valid values are CHROME and FIREFOX.
	// The multiple browsers list on which synthetic monitors will run. Valid values are array of CHROME,and FIREFOX
	// +listType=set
	Browsers []*string `json:"browsers,omitempty" tf:"browsers,omitempty"`

	// Monitor should skip default HEAD request and instead use GET verb in check.
	// Bypass HEAD request.
	BypassHeadRequest *bool `json:"bypassHeadRequest,omitempty" tf:"bypass_head_request,omitempty"`

	// Custom headers to use in monitor job. See Nested custom_header blocks below for details.
	// Custom headers to use in monitor job
	CustomHeader []CustomHeaderInitParameters `json:"customHeader,omitempty" tf:"custom_header,omitempty"`

	// Device emulation orientation field. Valid values are LANDSCAPE and PORTRAIT.
	// The device orientation the user would like to represent. Valid values are LANDSCAPE, PORTRAIT, or NONE.
	DeviceOrientation *string `json:"deviceOrientation,omitempty" tf:"device_orientation,omitempty"`

	// Device emulation type field. Valid values are MOBILE and TABLET.
	// The device type that a user can select. Valid values are MOBILE, TABLET, or NONE.
	DeviceType *string `json:"deviceType,omitempty" tf:"device_type,omitempty"`

	// The multiple devices list on which synthetic monitors will run. Valid values are DESKTOP, MOBILE_LANDSCAPE, MOBILE_PORTRAIT, TABLET_LANDSCAPE and TABLET_PORTRAIT.
	// The multiple devices list on which synthetic monitors will run. Valid values are array of DESKTOP, MOBILE_LANDSCAPE, MOBILE_PORTRAIT, TABLET_LANDSCAPE and TABLET_PORTRAIT
	// +listType=set
	Devices []*string `json:"devices,omitempty" tf:"devices,omitempty"`

	// Capture a screenshot during job execution.
	// Capture a screenshot during job execution
	EnableScreenshotOnFailureAndScript *bool `json:"enableScreenshotOnFailureAndScript,omitempty" tf:"enable_screenshot_on_failure_and_script,omitempty"`

	// The location the monitor will run from. Accepts a list of private location GUIDs. At least one of either locations_public or locations_private is required.
	// The locations in which this monitor should be run.
	// +listType=set
	LocationsPrivate []*string `json:"locationsPrivate,omitempty" tf:"locations_private,omitempty"`

	// The location the monitor will run from. Check out this page for a list of valid public locations. You don't need the AWS_ prefix as the provider uses NerdGraph. At least one of either locations_public or location_private is required.
	// The locations in which this monitor should be run.
	// +listType=set
	LocationsPublic []*string `json:"locationsPublic,omitempty" tf:"locations_public,omitempty"`

	// The human-readable identifier for the monitor.
	// The title of this monitor.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The interval at which this monitor should run. Valid values are EVERY_MINUTE, EVERY_5_MINUTES, EVERY_10_MINUTES, EVERY_15_MINUTES, EVERY_30_MINUTES, EVERY_HOUR, EVERY_6_HOURS, EVERY_12_HOURS, or EVERY_DAY.
	// The interval at which this monitor should run. Valid values are EVERY_MINUTE, EVERY_5_MINUTES, EVERY_10_MINUTES, EVERY_15_MINUTES, EVERY_30_MINUTES, EVERY_HOUR, EVERY_6_HOURS, EVERY_12_HOURS, or EVERY_DAY.
	Period *string `json:"period,omitempty" tf:"period,omitempty"`

	// The runtime that the monitor will use to run jobs (CHROME_BROWSER).
	// The runtime type that the monitor will run
	RuntimeType *string `json:"runtimeType,omitempty" tf:"runtime_type,omitempty"`

	// The specific version of the runtime type selected. Use LATEST to automatically use the latest Chrome version (currently 146, will be automatically upgraded to Chrome 147 or higher on Aug 18, 2026, updated automatically as new versions are released). We recommend explicitly setting runtime_type_version = "LATEST" in your configuration to avoid drift.
	// The specific version of the runtime type selected
	RuntimeTypeVersion *string `json:"runtimeTypeVersion,omitempty" tf:"runtime_type_version,omitempty"`

	// The programing language that should execute the script.
	// The programing language that should execute the script
	ScriptLanguage *string `json:"scriptLanguage,omitempty" tf:"script_language,omitempty"`

	// The run state of the monitor. (ENABLED or DISABLED).
	// The monitor status (ENABLED or DISABLED).
	Status *string `json:"status,omitempty" tf:"status,omitempty"`

	// The tags that will be associated with the monitor. See Nested tag blocks below for details.
	// The tags that will be associated with the monitor
	Tag []TagInitParameters `json:"tag,omitempty" tf:"tag,omitempty"`

	// Categorize redirects during a monitor job as a failure.
	// Fail the monitor check if redirected.
	TreatRedirectAsFailure *bool `json:"treatRedirectAsFailure,omitempty" tf:"treat_redirect_as_failure,omitempty"`

	// The monitor type. Valid values are SIMPLE and BROWSER.
	// The monitor type. Valid values are SIMPLE AND BROWSER.
	Type *string `json:"type,omitempty" tf:"type,omitempty"`

	// The URI the monitor runs against.
	// The URI for the monitor to hit.
	URI *string `json:"uri,omitempty" tf:"uri,omitempty"`

	// A boolean attribute to be set true by the customer, if they would like to use the unsupported legacy runtime of Synthetic Monitors by means of an exemption given until the October 22, 2024 Legacy Runtime EOL.43.0 to disallow using the legacy runtime with new monitors. This would, hence, allow creation of monitors in the legacy runtime until the October 22, 2024 Legacy Runtime EOL, if exempt by the API.
	UseUnsupportedLegacyRuntime *bool `json:"useUnsupportedLegacyRuntime,omitempty" tf:"use_unsupported_legacy_runtime,omitempty"`

	// Validation text for monitor to search for at given URI.
	// The string to validate against in the response.
	ValidationString *string `json:"validationString,omitempty" tf:"validation_string,omitempty"`

	// Monitor should validate SSL certificate chain.
	// Verify SSL.
	VerifySSL *bool `json:"verifySsl,omitempty" tf:"verify_ssl,omitempty"`
}

type MonitorObservation struct {

	// The account in which the Synthetics monitor will be created.
	// ID of the newrelic account
	AccountID *float64 `json:"accountId,omitempty" tf:"account_id,omitempty"`

	// The multiple browsers list on which synthetic monitors will run. Valid values are CHROME and FIREFOX.
	// The multiple browsers list on which synthetic monitors will run. Valid values are array of CHROME,and FIREFOX
	// +listType=set
	Browsers []*string `json:"browsers,omitempty" tf:"browsers,omitempty"`

	// Monitor should skip default HEAD request and instead use GET verb in check.
	// Bypass HEAD request.
	BypassHeadRequest *bool `json:"bypassHeadRequest,omitempty" tf:"bypass_head_request,omitempty"`

	// Custom headers to use in monitor job. See Nested custom_header blocks below for details.
	// Custom headers to use in monitor job
	CustomHeader []CustomHeaderObservation `json:"customHeader,omitempty" tf:"custom_header,omitempty"`

	// Device emulation orientation field. Valid values are LANDSCAPE and PORTRAIT.
	// The device orientation the user would like to represent. Valid values are LANDSCAPE, PORTRAIT, or NONE.
	DeviceOrientation *string `json:"deviceOrientation,omitempty" tf:"device_orientation,omitempty"`

	// Device emulation type field. Valid values are MOBILE and TABLET.
	// The device type that a user can select. Valid values are MOBILE, TABLET, or NONE.
	DeviceType *string `json:"deviceType,omitempty" tf:"device_type,omitempty"`

	// The multiple devices list on which synthetic monitors will run. Valid values are DESKTOP, MOBILE_LANDSCAPE, MOBILE_PORTRAIT, TABLET_LANDSCAPE and TABLET_PORTRAIT.
	// The multiple devices list on which synthetic monitors will run. Valid values are array of DESKTOP, MOBILE_LANDSCAPE, MOBILE_PORTRAIT, TABLET_LANDSCAPE and TABLET_PORTRAIT
	// +listType=set
	Devices []*string `json:"devices,omitempty" tf:"devices,omitempty"`

	// Capture a screenshot during job execution.
	// Capture a screenshot during job execution
	EnableScreenshotOnFailureAndScript *bool `json:"enableScreenshotOnFailureAndScript,omitempty" tf:"enable_screenshot_on_failure_and_script,omitempty"`

	// The ID (GUID) of the Synthetics monitor that the script is attached to.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// The location the monitor will run from. Accepts a list of private location GUIDs. At least one of either locations_public or locations_private is required.
	// The locations in which this monitor should be run.
	// +listType=set
	LocationsPrivate []*string `json:"locationsPrivate,omitempty" tf:"locations_private,omitempty"`

	// The location the monitor will run from. Check out this page for a list of valid public locations. You don't need the AWS_ prefix as the provider uses NerdGraph. At least one of either locations_public or location_private is required.
	// The locations in which this monitor should be run.
	// +listType=set
	LocationsPublic []*string `json:"locationsPublic,omitempty" tf:"locations_public,omitempty"`

	// The monitor id of the Synthetics monitor (not to be confused with the GUID of the monitor).
	// ID of the monitor
	MonitorID *string `json:"monitorId,omitempty" tf:"monitor_id,omitempty"`

	// The human-readable identifier for the monitor.
	// The title of this monitor.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The interval at which this monitor should run. Valid values are EVERY_MINUTE, EVERY_5_MINUTES, EVERY_10_MINUTES, EVERY_15_MINUTES, EVERY_30_MINUTES, EVERY_HOUR, EVERY_6_HOURS, EVERY_12_HOURS, or EVERY_DAY.
	// The interval at which this monitor should run. Valid values are EVERY_MINUTE, EVERY_5_MINUTES, EVERY_10_MINUTES, EVERY_15_MINUTES, EVERY_30_MINUTES, EVERY_HOUR, EVERY_6_HOURS, EVERY_12_HOURS, or EVERY_DAY.
	Period *string `json:"period,omitempty" tf:"period,omitempty"`

	// The interval in minutes at which Synthetic monitor should run.
	// The interval in minutes at which this monitor should run.
	PeriodInMinutes *float64 `json:"periodInMinutes,omitempty" tf:"period_in_minutes,omitempty"`

	// The runtime that the monitor will use to run jobs (CHROME_BROWSER).
	// The runtime type that the monitor will run
	RuntimeType *string `json:"runtimeType,omitempty" tf:"runtime_type,omitempty"`

	// The specific version of the runtime type selected. Use LATEST to automatically use the latest Chrome version (currently 146, will be automatically upgraded to Chrome 147 or higher on Aug 18, 2026, updated automatically as new versions are released). We recommend explicitly setting runtime_type_version = "LATEST" in your configuration to avoid drift.
	// The specific version of the runtime type selected
	RuntimeTypeVersion *string `json:"runtimeTypeVersion,omitempty" tf:"runtime_type_version,omitempty"`

	// The programing language that should execute the script.
	// The programing language that should execute the script
	ScriptLanguage *string `json:"scriptLanguage,omitempty" tf:"script_language,omitempty"`

	// The run state of the monitor. (ENABLED or DISABLED).
	// The monitor status (ENABLED or DISABLED).
	Status *string `json:"status,omitempty" tf:"status,omitempty"`

	// The tags that will be associated with the monitor. See Nested tag blocks below for details.
	// The tags that will be associated with the monitor
	Tag []TagObservation `json:"tag,omitempty" tf:"tag,omitempty"`

	// Categorize redirects during a monitor job as a failure.
	// Fail the monitor check if redirected.
	TreatRedirectAsFailure *bool `json:"treatRedirectAsFailure,omitempty" tf:"treat_redirect_as_failure,omitempty"`

	// The monitor type. Valid values are SIMPLE and BROWSER.
	// The monitor type. Valid values are SIMPLE AND BROWSER.
	Type *string `json:"type,omitempty" tf:"type,omitempty"`

	// The URI the monitor runs against.
	// The URI for the monitor to hit.
	URI *string `json:"uri,omitempty" tf:"uri,omitempty"`

	// A boolean attribute to be set true by the customer, if they would like to use the unsupported legacy runtime of Synthetic Monitors by means of an exemption given until the October 22, 2024 Legacy Runtime EOL.43.0 to disallow using the legacy runtime with new monitors. This would, hence, allow creation of monitors in the legacy runtime until the October 22, 2024 Legacy Runtime EOL, if exempt by the API.
	UseUnsupportedLegacyRuntime *bool `json:"useUnsupportedLegacyRuntime,omitempty" tf:"use_unsupported_legacy_runtime,omitempty"`

	// Validation text for monitor to search for at given URI.
	// The string to validate against in the response.
	ValidationString *string `json:"validationString,omitempty" tf:"validation_string,omitempty"`

	// Monitor should validate SSL certificate chain.
	// Verify SSL.
	VerifySSL *bool `json:"verifySsl,omitempty" tf:"verify_ssl,omitempty"`
}

type MonitorParameters struct {

	// The account in which the Synthetics monitor will be created.
	// ID of the newrelic account
	// +kubebuilder:validation:Optional
	AccountID *float64 `json:"accountId,omitempty" tf:"account_id,omitempty"`

	// The multiple browsers list on which synthetic monitors will run. Valid values are CHROME and FIREFOX.
	// The multiple browsers list on which synthetic monitors will run. Valid values are array of CHROME,and FIREFOX
	// +kubebuilder:validation:Optional
	// +listType=set
	Browsers []*string `json:"browsers,omitempty" tf:"browsers,omitempty"`

	// Monitor should skip default HEAD request and instead use GET verb in check.
	// Bypass HEAD request.
	// +kubebuilder:validation:Optional
	BypassHeadRequest *bool `json:"bypassHeadRequest,omitempty" tf:"bypass_head_request,omitempty"`

	// Custom headers to use in monitor job. See Nested custom_header blocks below for details.
	// Custom headers to use in monitor job
	// +kubebuilder:validation:Optional
	CustomHeader []CustomHeaderParameters `json:"customHeader,omitempty" tf:"custom_header,omitempty"`

	// Device emulation orientation field. Valid values are LANDSCAPE and PORTRAIT.
	// The device orientation the user would like to represent. Valid values are LANDSCAPE, PORTRAIT, or NONE.
	// +kubebuilder:validation:Optional
	DeviceOrientation *string `json:"deviceOrientation,omitempty" tf:"device_orientation,omitempty"`

	// Device emulation type field. Valid values are MOBILE and TABLET.
	// The device type that a user can select. Valid values are MOBILE, TABLET, or NONE.
	// +kubebuilder:validation:Optional
	DeviceType *string `json:"deviceType,omitempty" tf:"device_type,omitempty"`

	// The multiple devices list on which synthetic monitors will run. Valid values are DESKTOP, MOBILE_LANDSCAPE, MOBILE_PORTRAIT, TABLET_LANDSCAPE and TABLET_PORTRAIT.
	// The multiple devices list on which synthetic monitors will run. Valid values are array of DESKTOP, MOBILE_LANDSCAPE, MOBILE_PORTRAIT, TABLET_LANDSCAPE and TABLET_PORTRAIT
	// +kubebuilder:validation:Optional
	// +listType=set
	Devices []*string `json:"devices,omitempty" tf:"devices,omitempty"`

	// Capture a screenshot during job execution.
	// Capture a screenshot during job execution
	// +kubebuilder:validation:Optional
	EnableScreenshotOnFailureAndScript *bool `json:"enableScreenshotOnFailureAndScript,omitempty" tf:"enable_screenshot_on_failure_and_script,omitempty"`

	// The location the monitor will run from. Accepts a list of private location GUIDs. At least one of either locations_public or locations_private is required.
	// The locations in which this monitor should be run.
	// +kubebuilder:validation:Optional
	// +listType=set
	LocationsPrivate []*string `json:"locationsPrivate,omitempty" tf:"locations_private,omitempty"`

	// The location the monitor will run from. Check out this page for a list of valid public locations. You don't need the AWS_ prefix as the provider uses NerdGraph. At least one of either locations_public or location_private is required.
	// The locations in which this monitor should be run.
	// +kubebuilder:validation:Optional
	// +listType=set
	LocationsPublic []*string `json:"locationsPublic,omitempty" tf:"locations_public,omitempty"`

	// The human-readable identifier for the monitor.
	// The title of this monitor.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The interval at which this monitor should run. Valid values are EVERY_MINUTE, EVERY_5_MINUTES, EVERY_10_MINUTES, EVERY_15_MINUTES, EVERY_30_MINUTES, EVERY_HOUR, EVERY_6_HOURS, EVERY_12_HOURS, or EVERY_DAY.
	// The interval at which this monitor should run. Valid values are EVERY_MINUTE, EVERY_5_MINUTES, EVERY_10_MINUTES, EVERY_15_MINUTES, EVERY_30_MINUTES, EVERY_HOUR, EVERY_6_HOURS, EVERY_12_HOURS, or EVERY_DAY.
	// +kubebuilder:validation:Optional
	Period *string `json:"period,omitempty" tf:"period,omitempty"`

	// The runtime that the monitor will use to run jobs (CHROME_BROWSER).
	// The runtime type that the monitor will run
	// +kubebuilder:validation:Optional
	RuntimeType *string `json:"runtimeType,omitempty" tf:"runtime_type,omitempty"`

	// The specific version of the runtime type selected. Use LATEST to automatically use the latest Chrome version (currently 146, will be automatically upgraded to Chrome 147 or higher on Aug 18, 2026, updated automatically as new versions are released). We recommend explicitly setting runtime_type_version = "LATEST" in your configuration to avoid drift.
	// The specific version of the runtime type selected
	// +kubebuilder:validation:Optional
	RuntimeTypeVersion *string `json:"runtimeTypeVersion,omitempty" tf:"runtime_type_version,omitempty"`

	// The programing language that should execute the script.
	// The programing language that should execute the script
	// +kubebuilder:validation:Optional
	ScriptLanguage *string `json:"scriptLanguage,omitempty" tf:"script_language,omitempty"`

	// The run state of the monitor. (ENABLED or DISABLED).
	// The monitor status (ENABLED or DISABLED).
	// +kubebuilder:validation:Optional
	Status *string `json:"status,omitempty" tf:"status,omitempty"`

	// The tags that will be associated with the monitor. See Nested tag blocks below for details.
	// The tags that will be associated with the monitor
	// +kubebuilder:validation:Optional
	Tag []TagParameters `json:"tag,omitempty" tf:"tag,omitempty"`

	// Categorize redirects during a monitor job as a failure.
	// Fail the monitor check if redirected.
	// +kubebuilder:validation:Optional
	TreatRedirectAsFailure *bool `json:"treatRedirectAsFailure,omitempty" tf:"treat_redirect_as_failure,omitempty"`

	// The monitor type. Valid values are SIMPLE and BROWSER.
	// The monitor type. Valid values are SIMPLE AND BROWSER.
	// +kubebuilder:validation:Optional
	Type *string `json:"type,omitempty" tf:"type,omitempty"`

	// The URI the monitor runs against.
	// The URI for the monitor to hit.
	// +kubebuilder:validation:Optional
	URI *string `json:"uri,omitempty" tf:"uri,omitempty"`

	// A boolean attribute to be set true by the customer, if they would like to use the unsupported legacy runtime of Synthetic Monitors by means of an exemption given until the October 22, 2024 Legacy Runtime EOL.43.0 to disallow using the legacy runtime with new monitors. This would, hence, allow creation of monitors in the legacy runtime until the October 22, 2024 Legacy Runtime EOL, if exempt by the API.
	// +kubebuilder:validation:Optional
	UseUnsupportedLegacyRuntime *bool `json:"useUnsupportedLegacyRuntime,omitempty" tf:"use_unsupported_legacy_runtime,omitempty"`

	// Validation text for monitor to search for at given URI.
	// The string to validate against in the response.
	// +kubebuilder:validation:Optional
	ValidationString *string `json:"validationString,omitempty" tf:"validation_string,omitempty"`

	// Monitor should validate SSL certificate chain.
	// Verify SSL.
	// +kubebuilder:validation:Optional
	VerifySSL *bool `json:"verifySsl,omitempty" tf:"verify_ssl,omitempty"`
}

type TagInitParameters struct {

	// Name of the tag key.
	// Name of the tag key
	Key *string `json:"key,omitempty" tf:"key,omitempty"`

	// Values associated with the tag key.
	// Values associated with the tag key
	Values []*string `json:"values,omitempty" tf:"values,omitempty"`
}

type TagObservation struct {

	// Name of the tag key.
	// Name of the tag key
	Key *string `json:"key,omitempty" tf:"key,omitempty"`

	// Values associated with the tag key.
	// Values associated with the tag key
	Values []*string `json:"values,omitempty" tf:"values,omitempty"`
}

type TagParameters struct {

	// Name of the tag key.
	// Name of the tag key
	// +kubebuilder:validation:Optional
	Key *string `json:"key" tf:"key,omitempty"`

	// Values associated with the tag key.
	// Values associated with the tag key
	// +kubebuilder:validation:Optional
	Values []*string `json:"values" tf:"values,omitempty"`
}

// MonitorSpec defines the desired state of Monitor
type MonitorSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            MonitorParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider MonitorInitParameters `json:"initProvider,omitempty"`
}

// MonitorStatus defines the observed state of Monitor.
type MonitorStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               MonitorObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Monitor is the Schema for the Monitors API. Create and manage a Synthetics monitor in New Relic.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,newrelic}
type Monitor struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.status) || (has(self.initProvider) && has(self.initProvider.status))",message="spec.forProvider.status is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.type) || (has(self.initProvider) && has(self.initProvider.type))",message="spec.forProvider.type is a required parameter"
	Spec   MonitorSpec   `json:"spec"`
	Status MonitorStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// MonitorList contains a list of Monitors
type MonitorList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Monitor `json:"items"`
}

// Repository type metadata.
var (
	Monitor_Kind             = "Monitor"
	Monitor_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Monitor_Kind}.String()
	Monitor_KindAPIVersion   = Monitor_Kind + "." + CRDGroupVersion.String()
	Monitor_GroupVersionKind = CRDGroupVersion.WithKind(Monitor_Kind)
)

func init() {
	SchemeBuilder.Register(&Monitor{}, &MonitorList{})
}
