/*
Copyright 2024 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

// Package namespaced contains Kubernetes API for the provider.
package namespaced

import (
	"k8s.io/apimachinery/pkg/runtime"

	v1alpha1 "github.com/crossplane-contrib/crossplane-provider-newrelic/apis/namespaced/alert/v1alpha1"
	v1alpha1dashboard "github.com/crossplane-contrib/crossplane-provider-newrelic/apis/namespaced/dashboard/v1alpha1"
	v1alpha1log "github.com/crossplane-contrib/crossplane-provider-newrelic/apis/namespaced/log/v1alpha1"
	v1alpha1nrql "github.com/crossplane-contrib/crossplane-provider-newrelic/apis/namespaced/nrql/v1alpha1"
	v1alpha1pipeline "github.com/crossplane-contrib/crossplane-provider-newrelic/apis/namespaced/pipeline/v1alpha1"
	v1alpha1namespaced "github.com/crossplane-contrib/crossplane-provider-newrelic/apis/namespaced/v1alpha1"
	v1beta1 "github.com/crossplane-contrib/crossplane-provider-newrelic/apis/namespaced/v1beta1"
	v1alpha1workflow "github.com/crossplane-contrib/crossplane-provider-newrelic/apis/namespaced/workflow/v1alpha1"
)

func init() {
	// Register the types with the Scheme so the components can map objects to GroupVersionKinds and back
	AddToSchemes = append(AddToSchemes,
		v1alpha1.SchemeBuilder.AddToScheme,
		v1alpha1dashboard.SchemeBuilder.AddToScheme,
		v1alpha1log.SchemeBuilder.AddToScheme,
		v1alpha1nrql.SchemeBuilder.AddToScheme,
		v1alpha1pipeline.SchemeBuilder.AddToScheme,
		v1alpha1namespaced.SchemeBuilder.AddToScheme,
		v1beta1.SchemeBuilder.AddToScheme,
		v1alpha1workflow.SchemeBuilder.AddToScheme,
	)
}

// AddToSchemes may be used to add all resources defined in the project to a Scheme
var AddToSchemes runtime.SchemeBuilder

// AddToScheme adds all Resources to the Scheme
func AddToScheme(s *runtime.Scheme) error {
	return AddToSchemes.AddToScheme(s)
}
