---
apiVersion: nrql.newrelic.upbound.io/v1alpha1
kind: DropRule
metadata:
  annotations:
    meta.upbound.io/example-id: nrql/v1alpha1/droprule
  labels:
    testing.upbound.io/example-name: example-droprule
  name: example-droprule
spec:
  forProvider:
    action: drop_data
    description: Drops all data for MyCustomEvent that comes from the LoadGeneratingApp
      in the dev environment, because there is too much and we don’t look at it.
    nrql: SELECT * FROM MyCustomEvent WHERE appName='LoadGeneratingApp' AND environment='development'
