/*
Copyright 2026 Upbound Inc.
*/
// Code generated by angryjet. DO NOT EDIT.
// Code transformed by upjet. DO NOT EDIT.

package v1alpha1

import (
	"context"
	apisresolver "github.com/crossplane-contrib/crossplane-provider-newrelic/internal/apis"
	reference "github.com/crossplane/crossplane-runtime/v2/pkg/reference"
	xpresource "github.com/crossplane/crossplane-runtime/v2/pkg/resource"
	errors "github.com/pkg/errors"
	client "sigs.k8s.io/controller-runtime/pkg/client"
)

func (mg *Workflow) ResolveReferences( // ResolveReferences of this Workflow.
	ctx context.Context, c client.Reader) error {
	var m xpresource.Managed
	var l xpresource.ManagedList
	r := reference.NewAPIResolver(c, mg)

	var rsp reference.ResolutionResponse
	var err error

	for i3 := 0; i3 < len(mg.Spec.ForProvider.Destination); i3++ {
		{
			m, l, err = apisresolver.GetManagedResource("alert.newrelic.upbound.io", "v1alpha1", "Channel", "ChannelList")
			if err != nil {
				return errors.Wrap(err, "failed to get the reference target managed resource and its list for reference resolution")
			}
			rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
				CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.Destination[i3].ChannelID),
				Extract:      reference.ExternalName(),
				Namespace:    mg.GetNamespace(),
				Reference:    mg.Spec.ForProvider.Destination[i3].ChannelIDRef,
				Selector:     mg.Spec.ForProvider.Destination[i3].ChannelIDSelector,
				To:           reference.To{List: l, Managed: m},
			})
		}
		if err != nil {
			return errors.Wrap(err, "mg.Spec.ForProvider.Destination[i3].ChannelID")
		}
		mg.Spec.ForProvider.Destination[i3].ChannelID = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.ForProvider.Destination[i3].ChannelIDRef = rsp.ResolvedReference

	}
	for i3 := 0; i3 < len(mg.Spec.InitProvider.Destination); i3++ {
		{
			m, l, err = apisresolver.GetManagedResource("alert.newrelic.upbound.io", "v1alpha1", "Channel", "ChannelList")
			if err != nil {
				return errors.Wrap(err, "failed to get the reference target managed resource and its list for reference resolution")
			}
			rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
				CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.Destination[i3].ChannelID),
				Extract:      reference.ExternalName(),
				Namespace:    mg.GetNamespace(),
				Reference:    mg.Spec.InitProvider.Destination[i3].ChannelIDRef,
				Selector:     mg.Spec.InitProvider.Destination[i3].ChannelIDSelector,
				To:           reference.To{List: l, Managed: m},
			})
		}
		if err != nil {
			return errors.Wrap(err, "mg.Spec.InitProvider.Destination[i3].ChannelID")
		}
		mg.Spec.InitProvider.Destination[i3].ChannelID = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.InitProvider.Destination[i3].ChannelIDRef = rsp.ResolvedReference

	}

	return nil
}
